# Generated by Django 4.2.7 on 2025-12-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialIssuedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_number', models.BigIntegerField(db_index=True)),
                ('transaction_hash', models.CharField(db_index=True, max_length=66, unique=True)),
                ('log_index', models.IntegerField()),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credential_id', models.BigIntegerField(db_index=True, unique=True)),
                ('student_wallet', models.CharField(db_index=True, max_length=42)),
                ('institution', models.CharField(db_index=True, max_length=42)),
                ('fingerprint', models.CharField(db_index=True, max_length=66)),
                ('metadata_uri', models.URLField(max_length=500)),
                ('encrypted_payload_uri', models.URLField(max_length=500)),
                ('expires_at', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'blockchain_credential_issued',
            },
        ),
        migrations.CreateModel(
            name='CredentialRevokedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_number', models.BigIntegerField(db_index=True)),
                ('transaction_hash', models.CharField(db_index=True, max_length=66, unique=True)),
                ('log_index', models.IntegerField()),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credential_id', models.BigIntegerField(db_index=True)),
                ('revoked_by', models.CharField(max_length=42)),
                ('reason_hash', models.CharField(max_length=66)),
                ('revoked_at', models.BigIntegerField()),
            ],
            options={
                'db_table': 'blockchain_credential_revoked',
            },
        ),
        migrations.CreateModel(
            name='IndexerState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('last_processed_block', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'blockchain_indexer_state',
            },
        ),
    ]
