# Generated by Django 4.2.7 on 2025-12-16 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_id', models.BigIntegerField(db_index=True, unique=True)),
                ('student_wallet', models.CharField(db_index=True, max_length=42)),
                ('fingerprint', models.CharField(db_index=True, max_length=66)),
                ('metadata_uri', models.URLField(max_length=500)),
                ('encrypted_payload_uri', models.URLField(max_length=500)),
                ('issued_at', models.BigIntegerField()),
                ('expires_at', models.BigIntegerField(blank=True, null=True)),
                ('revoked', models.BooleanField(default=False)),
                ('revoked_at', models.BigIntegerField(blank=True, null=True)),
                ('revocation_reason_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='institutions.institution')),
            ],
            options={
                'db_table': 'credentials',
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['student_wallet', '-issued_at'], name='credentials_student_62b342_idx'), models.Index(fields=['fingerprint'], name='credentials_fingerp_ef5d0c_idx')],
            },
        ),
    ]
