# Generated by Django 4.2.7 on 2025-12-17 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_institution_api_key_institution_user'),
        ('credentials', '0002_credential_degree_type_credential_diploma_file_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentVerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('passport_number', models.CharField(db_index=True, max_length=50)),
                ('student_wallet', models.CharField(db_index=True, max_length=42)),
                ('degree_type', models.CharField(max_length=100)),
                ('graduation_date', models.DateField()),
                ('diploma_file', models.FileField(upload_to='verification_requests/')),
                ('diploma_file_hash', models.CharField(db_index=True, max_length=66)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verifying', 'Verifying'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('hologram_ocr_result', models.JSONField(blank=True, null=True)),
                ('hologram_verified', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True)),
                ('share_link', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('credential', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_request', to='credentials.credential')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_requests', to='institutions.institution')),
            ],
            options={
                'db_table': 'student_verification_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['passport_number', '-created_at'], name='student_ver_passpor_ccceca_idx'), models.Index(fields=['status', '-created_at'], name='student_ver_status_90a476_idx')],
            },
        ),
    ]
