# Generated by Django 4.2.7 on 2025-12-16 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZKCircuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('circuit_type', models.CharField(choices=[('circom', 'Circom Circuit'), ('r1cs', 'R1CS Format'), ('commitment', 'Cryptographic Commitment')], max_length=50)),
                ('circuit_file_path', models.CharField(max_length=500)),
                ('circuit_hash', models.CharField(db_index=True, max_length=66, unique=True)),
                ('verification_key_path', models.CharField(blank=True, max_length=500, null=True)),
                ('verification_key_ipfs', models.CharField(blank=True, max_length=100, null=True)),
                ('proving_key_ipfs', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'zk_circuits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ZKProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_type', models.CharField(choices=[('credential_validity', 'Credential Validity Proof'), ('selective_disclosure', 'Selective Disclosure Proof'), ('range_proof', 'Range Proof (e.g., GPA > 3.5)'), ('membership_proof', 'Membership Proof (e.g., graduated from X)')], default='credential_validity', max_length=50)),
                ('proof_data', models.JSONField(blank=True, null=True)),
                ('proof_ipfs_hash', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('public_inputs', models.JSONField()),
                ('circuit_hash', models.CharField(db_index=True, max_length=66)),
                ('verification_key_ipfs', models.CharField(blank=True, max_length=100, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credential', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zkproof', to='credentials.credential')),
            ],
            options={
                'db_table': 'zkproofs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ZKProofVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verifier_address', models.CharField(blank=True, max_length=42, null=True)),
                ('verification_result', models.BooleanField()),
                ('verification_time', models.FloatField()),
                ('error_message', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='zkproof.zkproof')),
            ],
            options={
                'db_table': 'zkproof_verifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['proof', 'verification_result'], name='zkproof_ver_proof_i_ef5272_idx'), models.Index(fields=['created_at'], name='zkproof_ver_created_31a959_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='zkproof',
            index=models.Index(fields=['credential', 'proof_type'], name='zkproofs_credent_ff33ba_idx'),
        ),
        migrations.AddIndex(
            model_name='zkproof',
            index=models.Index(fields=['circuit_hash', 'is_valid'], name='zkproofs_circuit_f79963_idx'),
        ),
    ]
